---
- name: Ensure minectaft /opt dir exists
  file:
    path: /opt/minecraft
    state: directory
    mode: 0755

- name: Create minecraft user
  user:
    name: minecraft

- name: Copy minecraft systemd template
  template:
    src: minecraft_systemd.j2
    dest: /etc/systemd/system/minecraft.service

- name: Copy minecraft server environment Makefile
  template:
    src: Makefile.j2
    dest: /opt/minecraft/Makefile

- name: Setup minecraft server envinronment using Makefile
  make:
    chdir: /opt/minecraft
    target: configure

- name: Check if mcrcon exists
  make:
    chdir: /opt/minecraft
    target: check-mcrcon-already-installed
  register: mcrcon_installed

- name: Install mcrcon tool
  make:
    chdir: /opt/minecraft
    target: install-mcrcon
  when: mcrcon_installed.stdout == "false"

- name: Build default mcrcon target
  make:
    chdir: /opt/minecraft/tools/mcrcon
  when: mcrcon_installed.stdout == "false"
    
- name: Install mcrcon
  make:
    chdir: /opt/minecraft/tools/mcrcon
    target: install
  when: mcrcon_installed.stdout == "false"

- name: Configure rcon in server.properties
  make:
    chdir: /opt/minecraft
    target: configure-rcon
    
- name: Copy mcrcon-wrapper script
  template:
    src: mcrcon-wrapper.j2
    dest: /opt/minecraft/tools/mcrcon-wrapper.sh
    mode: '0755'

- name: Install latest minecraft version server jar
  make:
    chdir: /opt/minecraft
    target: update
    params:
      version: "{{ minecraft_version }}"
  when: minecraft_version

- name: Ensure folder permissions allows user minecraft
  file:
    path: /opt/minecraft
    state: directory
    recurse: yes
    owner: minecraft
    group: minecraft

- name: Restart minecraft service
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: minecraft
