---
- name: Install bind9 package
  apt:
    name: bind9
    state: present

- name: Install bind9utils package
  apt:
    name: bind9utils
    state: present



- name: Create bind9 log directory
  file:
    path: /var/log/named
    state: directory
    mode: '0745'
    owner: bind
    group: bind

- name: Create bind9 log file
  file:
    path: /var/log/named/named.log
    state: file
    mode: '0745'
    owner: bind
    group: bind

- name: Copy logrotate
  template:
    src: logrotate-bind.log.j2
    dest: /etc/logrotate.d/bind.log
    owner: root
    group: root
    mode: 644


- name: add user kevin to group bind
  user:
    name: kevin
    groups: bind
    append: yes

- name: clone bind9-config from github
  ansible.builtin.git:
    repo: 'https://github.com/kevinmidboe/bind9-config'
    dest: /tmp/bind
    force: true
    depth: 0

- name: overwrite /etc/bind folder from git
  copy:
    remote_src: true
    src: /tmp/bind
    dest: /etc
    force: true

- name: Make sure zones directory exists
  file:
    path: /etc/bind/zones
    state: directory
    owner: root
    group: bind
      
- name: Ensure bind folder permissions
  file:
    path: /etc/bind
    state: directory
    mode: "0640"
    owner: root
    group: bind
    recurse: yes

- name: Ensure bind directory executable permissions
  file:
    path: /etc/bind
    state: directory
    mode: "0750"
    owner: root
    group: bind

- name: Ensure bind zones directory executable permissions
  file:
    path: /etc/bind/zones
    state: directory
    mode: "0750"
    owner: root
    group: bind

