---
- name: Install bind9 package
  apt:
    name: bind9
    state: present

- name: Copy zone configuration for network/inventory
  template: src=db-{{ bind9_zone }}.j2 dest=/etc/bind/zones/db.{{ bind9_zone }} owner=root group=bind mode=644
 
- name: Copy named configuration for network/inventory
  template: src=named.conf.local-{{ bind9_zone }}.j2 dest=/etc/bind/named.conf.local owner=root group=bind mode=644
  
