---
- name: Install bind9 package
  apt:
    name: bind9
    state: present

- name: Install bind9utils package
  apt:
    name: bind9utils
    state: present

- name: Make sure zones directory exists
  file:
    path: /etc/bind/zones
    state: directory
    mode: '0745'
    owner: root
    group: bind

- name: Copy zone configuration for network/inventory
  template: src=db-{{ bind9_zone }}.j2 dest=/etc/bind/zones/db.{{ bind9_zone }} owner=root group=bind mode=644
 
- name: Copy named local configuration for network/inventory
  template: src=named.conf.local-{{ bind9_zone }}.j2 dest=/etc/bind/named.conf.local owner=root group=bind mode=644

- name: Copy named options configuration for network/inventory
  template: src=named.conf.options.j2 dest=/etc/bind/named.conf.options owner=root group=bind mode=644

  
