---
- name: Assure ssh keys dir exists
  file: path=/etc/ssh/keys state=directory

- name: Assure ssh user key dir exists 
  file: path=/etc/ssh/keys/{{ item }} state=directory
  with_items: "{{ ssh_keys_users | default([]) }}"

- name: User ssh keys
  template: src=ssh/keys/{{ item }}.j2 dest=/etc/ssh/keys/{{ item }}/authorized_keys owner={{ item }} mode=640
  with_items: "{{ ssh_keys_users | default([]) }}"

