---
- include: sshd_config.yml
  when: not ssh_skip_sshd_config

- include: ssh_config.yml
  when: not ssh_skip_ssh_config

- include: keys.yml
  when: not ssh_skip_ssh_keys

#- include: drone_keys.yml
#  when: 
#    - drone_ssh_client
#   - not ssh_skip_drone_keys

