---
- name: setup sshd_config
  include_tasks: sshd_config.yml
  when: not ssh_skip_sshd_config

- name: setup ssh_config
  include_tasks: ssh_config.yml
  when: not ssh_skip_ssh_config

- name: create required users
  include_tasks: create_users.yml
  when: not ssh_skip_ssh_keys

- name: sync ssh keys for users from vault
  include_tasks: keys.yml
  when: not ssh_skip_ssh_keys and has_vault

