---
- include: sshd_config.yml
  when: not ssh_skip_sshd_config

- include: ssh_config.yml
  when: not ssh_skip_ssh_config

- include: keys.yml
  when: not ssh_skip_ssh_keys

- include: append_to_root_key.yml
  when: (ssh_root_additional_key_users is defined) and (ssh_root_additional_key_users|length > 0)
