---
  - name: update debian hosts
    become: true
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400
    when:
      - ansible_os_family == 'Debian'

  - name: install sqlite3
    ansible.builtin.package:
      name: 
        - sqlite3
        - git
      state: present

  - name: create git user
    ansible.builtin.user:
      name: git
      shell: /bin/zsh
      create_home: true

  - name: download gitea executeable
    get_url:
      url: https://dl.gitea.io/gitea/1.17.3/gitea-1.17.3-linux-amd64
      dest: /tmp/gitea

  - name: move gitea executeable to bin
    ansible.builtin.copy:
      remote_src: true
      src: /tmp/gitea
      dest: /usr/local/bin/gitea
      mode: +x

  - name: create gitea lib custom directory
    ansible.builtin.file:
      path: /var/lib/gitea/custom
      state: directory
      mode: '0750'
      owner: git
      group: git

  - name: create gitea lib data directory
    ansible.builtin.file:
      path: /var/lib/gitea/data
      state: directory
      mode: '0750'
      owner: git
      group: git

  - name: create gitea lib log directory
    ansible.builtin.file:
      path: /var/lib/gitea/log
      state: directory
      mode: '0750'
      owner: git
      group: git

  - name: create gitea etc directory
    ansible.builtin.file:
      path: /etc/gitea
      state: directory
      mode: '0770'
      owner: root
      group: git

  - name: copy systemd template
    template:
      src: systemd.j2
      dest: /etc/systemd/system/gitea.service
      owner: root
      group: root
      mode: 644

  - name: Reload systemd deamon
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Enable gitea systemd service
    ansible.builtin.systemd:
      name: gitea.service
      state: started
