---
- name: Update apt
  apt:
    state: latest
    update_cache: true

- name: Install bacula package
  apt:
    name: bacula-client
    state: latest

- name: Assure spool bacula dir exists
  file:
    path: /var/spool/bacula
    state: directory
    mode: "0755"
    owner: bacula
    group: bacula
    recurse: yes

- name: Assure bacula dir exists
  file:
    path: /bacula
    state: directory
    mode: "0775"
    owner: bacula
    group: bacula
    recurse: yes

- name: Assure bacula restore dir exists
  file:
    path: /bacula/bacula-restores
    state: directory
    mode: "0755"
    owner: bacula
    group: bacula
    recurse: yes

- name: bconsole config
  template:
    src: bconsole_clio.j2
    dest: /etc/bacula/bconsole.conf
    owner: root
    group: bacula
    ownermode: 640

- name: bacula-fd config
  template:
    src: bacula-fd_clio.j2
    dest: /etc/bacula/bacula-fd.conf
    owner: root
    group: bacula
    ownermode: 640
