---
- name: Install gpg package
  apt:
    name: gpg
    state: present

- name: Add hashicorp GPG apt Key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add hashicorp repository
  apt_repository:
    repo: deb https://apt.releases.hashicorp.com focal main
    state: present

- name: Update apt
  apt:
    state: latest
    update_cache: true

- name: Install reqired packages
  apt:
    name: ['git', 'curl', 'wget', 'ca-certificates', 'vault']
    state: present

- name: Enable systemd vault service
  systemd:
    name: vault
    enabled: yes

# - name: Copy original vault systemd config
#   copy:
#     src: /lib/systemd/system/vault.service
#     dest: /lib/systemd/system/vault.service.original

# - name: Vault systemd config
#   template: src=vault_service.j2 dest=/lib/systemd/system/vault.service owner=root mode=640

- name: Reload systemd daemon
  systemd:
    daemon_reload: true

- name: Start systemd vault service
  systemd:
    name: vault
    state: started
