---
- name: Install gpg package
  apt:
    name: gpg
    state: present

- name: Add hashicorp GPG apt Key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add hashicorp repository
  apt_repository:
    repo: deb https://apt.releases.hashicorp.com focal main
    state: present

- name: Update apt
  apt:
    state: latest
    update_cache: true

- name: Install reqired packages
  apt:
    name: ['git', 'curl', 'wget', 'ca-certificates', 'vault']
    state: present

- name: Enable systemd vault service
  systemd:
    name: vault
    enabled: yes

- name: Copy original vault systemd config
  copy:
    src: /lib/systemd/system/vault.service
    dest: /lib/systemd/system/vault.service.original
    remote_src: yes

- name: Vault systemd config
  template: src=vault_service.j2 dest=/lib/systemd/system/vault.service owner=root mode=640

- name: Vault environment file
  template:
      src: vault_env.j2
      dest: /etc/vault.d/vault.env
      owner: vault
      group: vault
      mode: '0644'
  notify: restart vault

- name: Vault config file
  template:
      src: vault_http_hcl.j2
      dest: /etc/vault.d/vault.hcl
      owner: vault
      group: vault
      mode: '0644'
  notify: restart vault

- name: Vault raft data directory
  file:
    path: /etc/vault.d/vault/data
    state: directory
    mode: "0755"
    owner: vault
    group: vault
    recurse: yes

- name: Reload systemd daemon
  systemd:
    daemon_reload: true

- name: Start systemd vault service
  systemd:
    name: vault
    state: started