---
- name: Basic setup, brute force protection, firewall and log shipping
  hosts: schleppe
  roles:
    - role: roles/base                  # - Basic server setup and configuration
    - role: roles/fail2ban              # - SSH Brute force protection
    - role: roles/prox-qemu-agent       # - If proxmox vm insatll qemu agent
    - role: roles/firewall              # - Firewall, if firewall_enable is true
      enable_bacula_client_ufw_port: true
    - role: roles/ssh                   # - Sets up the ssh role, with keys, ssh_config and sshd_config
    - role: roles/oh-my-zsh
      users:
        - username: root
          oh_my_zsh:
            theme: robbyrussell
        # - username: kevin
        #   oh_my_zsh:
        #     theme: robbyrussell
    - role: roles/motd
#    - role: roles/bacula
