---
- name: Upgrade all machines
  hosts: all

  tasks:
    - name: update debian hosts
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
      when:
        - ansible_os_family == 'Debian'


