---
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto
  register: package_facts

- name: Check current {{ package_name }} version installed
  debug:
    var: package_facts.ansible_facts.packages['{{ package_name }}'][0].version.split('-')[0]
  register: version_check

- name: Print the current version of {{ package_name }}
  debug:
    msg: "{{ package_name }} version installed: {{ version_check[\"package_facts.ansible_facts.packages['xz-utils'][0].version.split('-')[0]\"] }}"

- name: Install safe version of {{ package_name }}
  ansible.builtin.package:
    name: '{{ package_name }}={{ safe_version }}'
    state: present
  when: version_check==non_safe_version1 or version_check==non_safe_version2
