# APT Related tasks for the base role
---
# Add repositories
- name: install apt https support
  apt: pkg=apt-transport-https state=latest update_cache=yes cache_valid_time=3600

- name: add nginx key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
  when: base_apt_nginx_repo

- name: add nginx repo
  apt_repository: repo='deb http://nginx.org/packages/mainline/debian/ jessie nginx' state=present
  when: base_apt_nginx_repo

- name: add nginx repo src
  apt_repository: repo='deb-src http://nginx.org/packages/debian/ jessie nginx' state=present
  when: base_apt_nginx_repo

- name: add node key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
  when: base_apt_node_repo

- name: add node repo
  apt_repository: repo='deb https://deb.nodesource.com/node{{ nodejs_version }} {{ debian_release }} main' state=present
  when: base_apt_node_repo

- name: add node repo src
  apt_repository: repo='deb-src https://deb.nodesource.com/node{{ nodejs_version}} {{ debian_release }} main' state=present
  when: base_apt_node_repo

- name: add postgres key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
  when: base_apt_postgresql_repo

- name: add postgres repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt {{ debian_release }}-pgdg main' state=present
  when: base_apt_postgresql_repo

- name: webupd8 java8 key
  apt_key: keyserver=keyserver.ubuntu.com id=EEA14886 state=present
  when: base_apt_java_repo

- name: webupd8 java8 repo
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main' state=present
  when: base_apt_java_repo

- name: webupd8 java8 repo src
  apt_repository: repo='deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main' state=present
  when: base_apt_java_repo

# Add packages
- name: install base packages
  apt: pkg={{ item }}
  with_items: "{{ base_packages }}"

# Dist-upgrade
- name: perform dist-upgrade
  apt: upgrade=dist